// AUTO-GENERATED by Scaffa - do not edit
// This file is the entrypoint for Scaffa's preview mode
import React from 'react';
import ReactDOM from 'react-dom/client';
import { ScaffaProvider } from '@scaffa/react-runtime-adapter';

// User Styles
import "./src/index.css";

// User Entry (App.tsx contains the Router)
import * as UserEntry from "./src/App.tsx";
const App = UserEntry.App || UserEntry.default;

const root = document.getElementById('root');
if (!root) throw new Error('Root element not found');

ReactDOM.createRoot(root).render(
  <React.StrictMode>
    <ScaffaProvider
      config={{
        adapterId: 'react',
        adapterVersion: '0.1.0',
        debug: true,
      }}
    >
      {App ? <App /> : <div style={{color: 'red', padding: '20px'}}>Error: No App or default export found in "./src/App.tsx"</div>}
    </ScaffaProvider>
  </React.StrictMode>
);
