// ─────────────────────────────────────────────────────────────────────────────
// Vite Runner (v0) - Real File Approach
// ─────────────────────────────────────────────────────────────────────────────
// This script runs in a separate process to manage the Vite dev server.
// It uses the PROJECT'S installed Vite version.
//
// KEY CHANGE: Instead of a virtual module, we write a real harness file to disk.
// This avoids all the plugin interaction issues with React Fast Refresh.
//
// NOTE: This is a source file (not a build artifact). Previously this was
// compiled from runner.ts, but since it used no TypeScript features, the
// .ts file was removed to simplify the build process.
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import path from "node:path";
import fs from "node:fs";
var require2 = createRequire(import.meta.url);
async function main() {
  const workspaceRoot = process.env.SCAFFA_ROOT || process.cwd();
  const entry = process.env.SCAFFA_ENTRY;
  const styles = JSON.parse(process.env.SCAFFA_STYLES || "[]");
  if (!entry) {
    console.error("[ViteRunner] Error: SCAFFA_ENTRY not set");
    process.exit(1);
  }
  console.log("[ViteRunner] Starting with config:", { entry, styles, workspaceRoot });
  const toRelative = (absPath) => {
    if (absPath.startsWith(workspaceRoot)) {
      return "." + absPath.slice(workspaceRoot.length);
    }
    return absPath;
  };
  const relativeEntry = toRelative(entry);
  const relativeStyles = styles.map(toRelative);
  console.log("[ViteRunner] Relative paths:", { entry: relativeEntry, styles: relativeStyles });
  try {
    const harnessPath = path.join(workspaceRoot, ".scaffa-harness.tsx");
    const harnessContent = `// AUTO-GENERATED by Scaffa - do not edit
// This file is the entrypoint for Scaffa's preview mode
import React from 'react';
import ReactDOM from 'react-dom/client';
import { ScaffaProvider } from '@scaffa/react-runtime-adapter';

// User Styles
${relativeStyles.map((s) => `import ${JSON.stringify(s)};`).join("\n")}

// User Entry (App.tsx contains the Router)
import * as UserEntry from ${JSON.stringify(relativeEntry)};
const App = UserEntry.App || UserEntry.default;

const root = document.getElementById('root');
if (!root) throw new Error('Root element not found');

ReactDOM.createRoot(root).render(
  <React.StrictMode>
    <ScaffaProvider
      config={{
        adapterId: 'react',
        adapterVersion: '0.1.0',
        debug: true,
      }}
    >
      {App ? <App /> : <div style={{color: 'red', padding: '20px'}}>Error: No App or default export found in ${JSON.stringify(relativeEntry)}</div>}
    </ScaffaProvider>
  </React.StrictMode>
);
`;
    fs.writeFileSync(harnessPath, harnessContent, "utf-8");
    console.log("[ViteRunner] Wrote harness file:", harnessPath);
    const cleanup = () => {
      try {
        if (fs.existsSync(harnessPath)) {
          fs.unlinkSync(harnessPath);
          console.log("[ViteRunner] Cleaned up harness file");
        }
      } catch (e) {
      }
    };
    process.on("exit", cleanup);
    process.on("SIGINT", () => {
      cleanup();
      process.exit();
    });
    process.on("SIGTERM", () => {
      cleanup();
      process.exit();
    });
    const vitePath = require2.resolve("vite", { paths: [workspaceRoot] });
    const viteModule = await import(pathToFileURL(vitePath).href);
    const vite = viteModule.default || viteModule;
    const projectConfig = await vite.loadConfigFromFile(
      { command: "serve", mode: "development" },
      void 0,
      workspaceRoot
    );
    const harnessPlugin = {
      name: "scaffa:harness",
      transformIndexHtml(html) {
        const scriptRegex = /<script\s+type="module"\s+src="[^"]+\.(tsx|ts)"><\/script>/;
        const match = html.match(scriptRegex);
        console.log("[ViteRunner] transformIndexHtml replacing:", match ? match[0] : "NO MATCH");
        return html.replace(
          scriptRegex,
          '<script type="module" src="/.scaffa-harness.tsx"></script>'
        );
      }
    };
    const randomPort = 3100 + Math.floor(Math.random() * 900);
    const myConfig = {
      root: workspaceRoot,
      server: {
        port: randomPort,
        strictPort: false
      },
      optimizeDeps: {
        include: ["react", "react-dom/client", "@scaffa/react-runtime-adapter"]
      }
    };
    const baseConfig = projectConfig?.config || {};
    const rawPlugins = Array.isArray(baseConfig.plugins) ? baseConfig.plugins : [];
    const allProjectPlugins = rawPlugins.flat(2).filter(Boolean);
    const projectPlugins = allProjectPlugins.filter(
      (p) => p?.name !== "vite:react-refresh" && p?.name !== "vite:react-babel"
    );
    console.log("[ViteRunner] Plugin info:", {
      allPlugins: allProjectPlugins.map((p) => p?.name).filter(Boolean),
      afterFilter: projectPlugins.map((p) => p?.name).filter(Boolean)
    });
    const jsxPlugin = {
      name: "scaffa:jsx",
      async transform(code, id) {
        if (!/\.(jsx|tsx)$/.test(id)) return null;
        if (id.includes("node_modules")) return null;
        const result = await vite.transformWithEsbuild(code, id, {
          loader: id.endsWith(".tsx") ? "tsx" : "jsx",
          jsx: "automatic",
          jsxImportSource: "react"
        });
        return {
          code: result.code,
          map: result.map
        };
      }
    };
    const mergedPlugins = [...projectPlugins, jsxPlugin, harnessPlugin];
    const { plugins: _, ...baseWithoutPlugins } = baseConfig;
    const finalConfig = vite.mergeConfig(baseWithoutPlugins, {
      ...myConfig,
      plugins: mergedPlugins
    });
    console.log("[ViteRunner] Starting Vite server...");
    const server = await vite.createServer(finalConfig);
    await server.listen();
    const address = server.httpServer?.address();
    const port = typeof address === "object" && address ? address.port : 0;
    console.log(`Local: http://localhost:${port}`);
    await new Promise(() => {
    });
  } catch (error) {
    console.error("[ViteRunner] Failed to start:", error);
    process.exit(1);
  }
}
main();
